#ifndef CONFIG_H
#define CONFIG_H
#define PI 3.141593

#define MAZE_SIZE 20

#define ANGULAR_STEP 5.0/180*PI
#define RADIUS_STEP 0.1

#define Y_WALL_COLOR RED
#define X_WALL_COLOR BLUE

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 540
#define HORIZON_HEIGHT 250

#endif // CONFIG_H